### ISSUE TITLE
Question on Sample

### ISSUE THREAD

**Issue by DotNetDublin** [adamfoneil/AzureFunctionApi#1]
This is really interesting as I've been curious about using Azure Functions.

One thing I was wondering how it worked was how do the Azure Functions call the database for the likes of CRUD operations?

Does it help or is it even mandatory for the database to be hosted in Azure?

Anyway I was just wondering if you have a sample that shows this?

**Comment by adamfoneil** [comment]
So, at the moment I have some integration [tests](https://github.com/adamfoneil/AzureFunctionApi/blob/master/Test.Server/CrudHandlerTests.cs) that show how this would work, but without an http connection. The method to look at is [PostWorkspaceInner](https://github.com/adamfoneil/AzureFunctionApi/blob/master/Test.Server/CrudHandlerTests.cs#L79). It uses an http request facade called [JsonApiRequest](https://github.com/adamfoneil/AzureFunctionApi/blob/master/AzureFunctionApi.Server/JsonApiRequest.cs) which abstracts a real http request via [FromHttpRequest](https://github.com/adamfoneil/AzureFunctionApi/blob/master/AzureFunctionApi.Server/JsonApiRequest.cs#L46).

The actual Azure function body would be [AzureFunctionHandler](https://github.com/adamfoneil/AzureFunctionApi/blob/master/AzureFunctionApi.Server/AzureFunctionHandler.cs). It has a repository object injected into it where the actual db interaction is done. This repository interface comes from my AO.Models project: [IRepository](https://github.com/adamfoneil/Models/blob/master/Models/Interfaces/IRepository.cs). My tests use several sample objects (dummy user, sample function) [here](https://github.com/adamfoneil/AzureFunctionApi/blob/master/Test.Server/SampleFunction.cs).

This all deserves a walkthrough vid to see how pieces fit together, and I'm not sure how practical it will be ultimately. I'm still unclear on authentication. Azure Functions have a different authentication story, I think, than regular web apps. I'm not quite sure what the latest advice there is. I use an [abstract authentication method](https://github.com/adamfoneil/AzureFunctionApi/blob/master/Test.Server/SampleFunction.cs#L26) that, for test purposes, assumes a hard-coded user.

**Comment by DotNetDublin** [comment]
Thanks for the response Adam. Will check out those links.
